-- Portfolio Project - ETL - Loading data

-- Inserts data in the table
INSERT INTO dw.DIM_STORE (Code, Name, City, State) VALUES
(1,  'Store A', 'São Paulo', 'SP'),
(2,  'Store B', 'Rio de Janeiro', 'RJ'),
(3,  'Store C', 'Belo Horizonte', 'MG'),
(4,  'Store D', 'Curitiba', 'PR'),
(5,  'Store E', 'Porto Alegre', 'RS'),
(6,  'Store F', 'Salvador', 'BA'),
(7,  'Store G', 'Recife', 'PE'),
(8,  'Store H', 'Fortaleza', 'CE'),
(9,  'Store I', 'Brasília', 'DF'),
(10, 'Store J', 'Goiânia', 'GO'),
(11, 'Store K', 'Manaus', 'AM'),
(12, 'Store L', 'Belém', 'PA'),
(13, 'Store M', 'Florianópolis', 'SC'),
(14, 'Store N', 'Vitória', 'ES'),
(15, 'Store O', 'Campo Grande', 'MS'),
(16, 'Store P', 'São Luís', 'MA'),
(17, 'Store Q', 'Natal', 'RN'),
(18, 'Store R', 'Maceió', 'AL');

-- Inserts data in the table
INSERT INTO dw.DIM_PRODUCT (SKU_Code, Name, Brand, Category) VALUES
(101, 'Smartwatch Plus', 'WearTech', 'Wearable Devices'),
(102, 'Wireless Router', 'NetLink', 'Networking Devices'),
(103, 'External Hard Drive 1TB', 'DataSafe', 'Storage Devices'),
(104, 'LED Desk Lamp', 'Brightech', 'Office Electronics'),
(105, 'Smart Thermostat', 'HomeTech', 'Smart Home Devices'),
(106, 'Phone Case with Stand', 'GripIt', 'Mobile Accessories'),
(107, 'Wireless Earbuds', 'SoundSync', 'Audio Devices'),
(108, 'Indoor Exercise Bike', 'FitPro', 'Fitness Equipment'),
(109, 'Smart Doorbell', 'RingIt', 'Smart Home Devices'),
(110, 'Car Charger', 'PowerUp', 'Mobile Accessories'),
(111, 'Electric Scooter', 'EcoRide', 'Transportation Devices'),
(112, 'Steam Iron', 'SteamMaster', 'Home Appliances'),
(113, 'Laptop Stand', 'ErgoTech', 'Computer Accessories'),
(114, 'Drill Set', 'PowerTool', 'Tools & Equipment'),
(115, 'All-in-One Desktop PC', 'TechMaster', 'Computers'),
(116, '4K Action Camera', 'ActionTech', 'Electronics'),
(117, 'Wireless Keyboard', 'KeyTech', 'Computer Accessories'),
(118, 'Robot Vacuum Cleaner', 'CleanBot', 'Smart Home Devices'),
(119, 'Cordless Drill', 'DrillPro', 'Tools & Equipment'),
(120, 'Gaming Mouse', 'GamerTech', 'Computer Accessories'),
(121, 'Smart LED Bulbs (Pack of 4)', 'IllumiTech', 'Smart Home Devices'),
(122, 'Mini Projector', 'ViewMax', 'Electronics'),
(123, 'USB Flash Drive 64GB', 'DataFlex', 'Storage Devices'),
(124, 'Portable Bluetooth Speaker', 'SoundWave', 'Audio Devices'),
(125, 'Fitness Tracker Watch', 'FitBit', 'Wearable Devices'),
(126, 'Solar-Powered Outdoor Lights (Set of 6)', 'SolarTech', 'Smart Home Devices'),
(127, 'External SSD 500GB', 'SpeedyDrive', 'Storage Devices'),
(128, 'Desk Organizer', 'OrganizeIt', 'Office Electronics'),
(129, 'Wireless Charging Pad', 'ChargeUp', 'Mobile Accessories'),
(130, 'Smart TV Box', 'StreamTech', 'Electronics'),
(131, 'Wireless Security Camera', 'SecureCam', 'Smart Home Devices'),
(132, 'Electric Toothbrush', 'OralCare', 'Home Appliances'),
(133, 'Bluetooth Speaker Lamp', 'LumiSound', 'Audio Devices'),
(134, 'Gaming Headset', 'GamerTech', 'Audio Devices'),
(135, 'Smartphone Gimbal Stabilizer', 'SteadyShot', 'Mobile Accessories'),
(136, 'Mini Fridge', 'ChillBox', 'Home Appliances'),
(137, 'Wireless Presenter Remote', 'SlidePro', 'Office Electronics'),
(138, 'Portable Power Bank 10000mAh', 'PowerUp', 'Mobile Accessories'),
(139, 'Yoga Mat', 'YogaGear', 'Fitness Equipment'),
(140, 'Smart WiFi Plug', 'PlugIt', 'Smart Home Devices'),
(141, 'Wireless Charging Stand', 'ChargePro', 'Mobile Accessories'),
(142, 'Handheld Vacuum Cleaner', 'QuickClean', 'Home Appliances'),
(143, 'USB-C Docking Station', 'DockTech', 'Computer Accessories'),
(144, 'Wi-Fi Range Extender', 'ExtendNet', 'Networking Devices'),
(145, 'Smart Weight Scale', 'WeighIn', 'Fitness Equipment'),
(146, 'Wireless Gaming Controller', 'GamerTech', 'Gaming Accessories'),
(147, 'Digital Picture Frame', 'FrameIt', 'Electronics'),
(148, 'External Blu-ray Drive', 'BluRayTech', 'Storage Devices'),
(149, 'Cordless Hair Dryer', 'BlowDry', 'Home Appliances'),
(150, 'Smart Mirror', 'MirrorTech', 'Smart Home Devices'),
(151, 'Wireless Barcode Scanner', 'ScanIt', 'Office Electronics'),
(152, 'Smart Lock', 'LockIt', 'Smart Home Devices'),
(153, 'Wireless Charging Car Mount', 'DriveCharge', 'Mobile Accessories'),
(154, 'Electric Kettle', 'KettlePro', 'Home Appliances'),
(155, 'Noise-Canceling Earbuds', 'QuietSound', 'Audio Devices'),
(156, 'Smart Ceiling Fan', 'CoolBreeze', 'Smart Home Devices'),
(157, 'Wireless Touchpad Keyboard', 'TouchType', 'Computer Accessories'),
(158, 'Cordless Hand Mixer', 'MixMaster', 'Home Appliances'),
(159, 'Smart Pet Feeder', 'PetTech', 'Smart Home Devices'),
(160, 'Wireless Presenter with Laser Pointer', 'LaserPro', 'Office Electronics'),
(161, 'External DVD Burner', 'DVDWriter', 'Storage Devices'),
(162, 'Portable Monitor', 'GoScreen', 'Computer Accessories'),
(163, 'Smart Water Bottle', 'HydraTech', 'Fitness Equipment'),
(164, 'Wireless Charging Mouse Pad', 'MousePad+', 'Computer Accessories'),
(165, 'Electric Wine Opener', 'WineTech', 'Home Appliances'),
(166, 'Smart Plugs (Pack of 2)', 'PlugIt', 'Smart Home Devices'),
(167, 'Wireless Weather Station', 'WeatherPro', 'Smart Home Devices'),
(168, 'Portable Blender', 'BlendGo', 'Home Appliances'),
(169, 'External SSD 1TB', 'SpeedyDrive', 'Storage Devices'),
(170, 'Wireless Headset', 'SoundStream', 'Audio Devices'),
(171, 'Smart Kitchen Scale', 'KitchenTech', 'Home Appliances'),
(172, 'Wireless Touchpad Mouse', 'TouchMouse', 'Computer Accessories'),
(173, 'Digital Voice Recorder', 'RecordIt', 'Office Electronics'),
(174, 'Smart Light Switch', 'SwitchIt', 'Smart Home Devices'),
(175, 'Portable Air Purifier', 'PurifyAir', 'Home Appliances'),
(176, 'Wireless Charging Desk Lamp', 'LumiCharge', 'Smart Home Devices'),
(177, 'Cordless Vacuum Cleaner', 'CleanPro', 'Home Appliances'),
(178, 'Smart Food Scale', 'WeighTech', 'Home Appliances'),
(179, 'Wireless Barcode Scanner', 'ScanTech', 'Office Electronics'),
(180, 'External HDD Enclosure', 'DataVault', 'Storage Devices'),
(181, 'Wireless HDMI Transmitter', 'HDMITech', 'Electronics'),
(182, 'Wireless Smart Door Lock', 'SecureLock', 'Smart Home Devices'),
(183, 'Portable Solar Charger', 'SolarCharge', 'Mobile Accessories'),
(185, 'Wireless Charging Alarm Clock', 'WakeUpCharge', 'Smart Home Devices'),
(185, 'External SSD 2TB', 'SpeedyDrive', 'Storage Devices'),
(186, 'Smart Glasses', 'SmartOptics', 'Wearable Devices'),
(187, 'Wireless Bluetooth Adapter', 'BlueLink', 'Computer Accessories'),
(188, 'Smart Remote Control', 'RemoteTech', 'Smart Home Devices'),
(189, 'Wireless Gaming Mouse', 'GamerTech', 'Gaming Accessories'),
(190, 'Smart Jump Rope', 'JumpTech', 'Fitness Equipment'),
(191, 'Wireless Charging Backpack', 'ChargePack', 'Mobile Accessories'),
(192, 'Smart Water Leak Detector', 'LeakAlert', 'Smart Home Devices'),
(193, 'Wireless Ergonomic Keyboard', 'ErgoType', 'Computer Accessories'),
(194, 'Portable Espresso Machine', 'EspressoGo', 'Home Appliances'),
(195, 'Wireless Charging Desk Organizer', 'ChargeCaddy', 'Office Electronics'),
(196, 'Smart Plant Monitor', 'PlantTech', 'Smart Home Devices'),
(197, 'Cordless Steam Iron', 'SteamPro', 'Home Appliances'),
(198, 'Smart Socket Adapter', 'SocketSmart', 'Smart Home Devices'),
(199, 'Wireless Presentation Clicker', 'SlideClick', 'Office Electronics'),
(200, 'Smart Air Quality Monitor', 'AirSense', 'Smart Home Devices'),
(201, 'Wireless Gaming Keyboard', 'GamerTech', 'Gaming Accessories'),
(202, 'Smart Clothes Steamer', 'SteamTech', 'Home Appliances'),
(203, 'Wireless Charging Mouse', 'ChargeMouse', 'Computer Accessories'),
(204, 'Smart Water Filter Pitcher', 'FilterIt', 'Home Appliances'),
(205, 'Wireless Charging Bedside Lamp', 'BedsideCharge', 'Smart Home Devices'),
(206, 'Smart Bike Lock', 'BikeGuard', 'Smart Home Devices'),
(207, 'Wireless Touchscreen Monitor', 'TouchScreenTech', 'Computer Accessories'),
(208, 'Smart Facial Recognition Doorbell', 'FaceBell', 'Smart Home Devices'),
(209, 'Wireless Charging Car Phone Holder', 'DriveCharge', 'Mobile Accessories'),
(210, 'Smart Yoga Mat', 'YogaTech', 'Fitness Equipment'),
(211, 'Wireless Presentation Remote', 'SlidePro', 'Office Electronics'),
(212, 'Smart Toothbrush', 'ToothTech', 'Home Appliances'),
(213, 'Wireless Charging Alarm Clock', 'WakeUpCharge', 'Smart Home Devices'),
(214, 'Smart Power Strip', 'PowerHub', 'Smart Home Devices'),
(215, 'Wireless Gamepad Controller', 'GamePadTech', 'Gaming Accessories'),
(216, 'Smart Indoor Herb Garden', 'HerbTech', 'Smart Home Devices'),
(217, 'Wireless Charging Nightstand', 'NightCharge', 'Smart Home Devices'),
(218, 'Smart Pet Camera', 'PetCam', 'Smart Home Devices'),
(219, 'Wireless Charging Phone Case', 'ChargeCase', 'Mobile Accessories'),
(220, 'Smart Ring', 'RingTech', 'Wearable Devices'),
(221, 'Wireless Charging Desk Fan', 'CoolCharge', 'Home Appliances'),
(222, 'Smart Contact Lens', 'LensTech', 'Wearable Devices'),
(223, 'Wireless Charging Vanity Mirror', 'VanityCharge', 'Home Appliances'),
(224, 'Smart Umbrella', 'UmbrellaTech', 'Smart Home Devices'),
(225, 'Wireless Charging Mouse Pad', 'ChargePad', 'Computer Accessories'),
(226, 'Smart Crock Pot', 'CrockTech', 'Home Appliances'),
(227, 'Wireless Charging Desk Organizer', 'ChargeCaddy', 'Office Electronics'),
(228, 'Smart Bed', 'BedTech', 'Home Appliances'),
(229, 'Wireless Charging Desk Lamp', 'DeskCharge', 'Office Electronics'),
(230, 'Smart Wallet', 'WalletTech', 'Mobile Accessories'),
(231, 'Wireless Charging Laptop Stand', 'LaptopCharge', 'Computer Accessories'),
(232, 'Wireless Charging Mouse Pad', 'ChargePad', 'Computer Accessories'),
(233, 'Smart Crock Pot', 'CrockTech', 'Home Appliances'),
(234, 'Wireless Charging Desk Organizer', 'ChargeCaddy', 'Office Electronics'),
(235, 'Smart Bed', 'BedTech', 'Home Appliances'),
(236, 'Wireless Charging Desk Lamp', 'DeskCharge', 'Office Electronics'),
(237, 'Smart Wallet', 'WalletTech', 'Mobile Accessories'),
(238, 'Wireless Charging Laptop Stand', 'LaptopCharge', 'Computer Accessories'),
(239, 'Smart Light Bulbs (Pack of 4)', 'IllumiSmart', 'Smart Home Devices'),
(240, 'Wireless Charging Mouse', 'ChargeMouse', 'Computer Accessories'),
(241, 'Smart Rice Cooker', 'RiceTech', 'Home Appliances'),
(242, 'Wireless Charging Desk Fan', 'CoolCharge', 'Home Appliances'),
(243, 'Smart Fitness Tracker', 'FitTrack', 'Wearable Devices'),
(244, 'Wireless Charging Pen Holder', 'PenCharge', 'Office Electronics'),
(245, 'Smart Coffee Maker', 'CoffeeTech', 'Home Appliances'),
(246, 'Wireless Charging Desk Clock', 'ClockCharge', 'Office Electronics'),
(247, 'Smart Air Purifier', 'PurifyTech', 'Home Appliances'),
(248, 'Wireless Charging Book Lamp', 'BookCharge', 'Office Electronics'),
(249, 'Smart Vacuum Cleaner', 'VacuumTech', 'Home Appliances'),
(250, 'Wireless Charging Desk Organizer', 'ChargeCaddy', 'Office Electronics');

-- Inserts data in the table
INSERT INTO dw.DIM_CLIENT (Client_ID, Name, Address, City, State) VALUES
(1, 'Belle Garrison', 'Rua Maria Santidade, 572', 'São Paulo', 'SP'),
(2, 'Noe Sellers', 'Rua Gutermberg, 785', 'Brasília', 'DF'),
(3, 'Mercy Berg', 'Rua Neves Cruz, 802', 'São Paulo', 'SP'),
(4, 'Cayson Powell', 'Rua Gustavo Silva, 500', 'Belo Horizonte', 'MG'),
(5, 'Vivian Burnett', 'Rua Gama Rei, 815', 'Manaus', 'AM'),
(6, 'Davis Armstrong', 'Rua das Estrelas, 422', 'Recife', 'PE'),
(7, 'Presley Mullins', 'Rua Van Deuterno, 632', 'Manaus', 'AM'),
(8, 'Allen Hayes', 'Rua das Laranjeiras, 299', 'Curitiba', 'PR'),
(9, 'Iris Harrell', 'Rua Maria Santidade, 640', 'Recife', 'PE'),
(10, 'Nelson Parrish', 'Rua Gama Rei, 397', 'São Paulo', 'SP'),
(11, 'Tiana Lim', 'Rua Maria Santidade, 573', 'Recife', 'PE'),
(12, 'Cal Garrison', 'Rua Arnaldo Cruz, 387', 'Belo Horizonte', 'MG'),
(13, 'Cadence Wilkins', 'Rua Santos Silva, 586', 'Recife', 'PE'),
(14, 'Yusuf Garrett', 'Rua Meireles Cunha, 701', 'Belo Horizonte', 'MG'),
(15, 'Tessa Luna', 'Rua Gustavo Silva, 620', 'Rio de Janeiro', 'RJ'),
(16, 'Erick Durham', 'Rua Maria Santidade, 143', 'Rio de Janeiro', 'RJ'),
(17, 'Tiffany Lang', 'Rua Gustavo Alegre, 717', 'Recife', 'PE'),
(18, 'Wells Wise', 'Rua das Borboletas, 149', 'Fortaleza', 'CE'),
(19, 'Mira Peralta', 'Rua Reinaldo Lemos, 719', 'Salvador', 'BA'),
(20, 'Dangelo Foster', 'Rua Marcelo dos Reis, 530', 'São Paulo', 'SP'),
(21, 'Brielle Bishop', 'Rua Reinaldo Lemos, 152', 'São Paulo', 'SP'),
(22, 'Paxton Wilcox', 'Rua Reinaldo Lemos, 744', 'Recife', 'PE'),
(23, 'Ashlyn Lowery', 'Rua Gutermberg, 781', 'Rio de Janeiro', 'RJ'),
(24, 'Jaxxon Huerta', 'Rua das Borboletas, 632', 'Belo Horizonte', 'MG'),
(25, 'Dulce Vargas', 'Rua Lopes Lima, 427', 'Belo Horizonte', 'MG'),
(26, 'Ryker Reilly', 'Rua Gustavo Alegre, 825', 'Porto Alegre', 'RS'),
(27, 'Tori Wolf', 'Rua das Estrelas, 849', 'Brasília', 'DF'),
(28, 'Jase Cummings', 'Rua das Laranjeiras, 338', 'Curitiba', 'PR'),
(29, 'Nylah Willis', 'Rua das Laranjeiras, 729', 'Porto Alegre', 'RS'),
(30, 'Remington Miranda', 'Rua Maria Santidade, 583', 'Manaus', 'AM'),
(31, 'Amina Jensen', 'Rua Reinaldo Lemos, 234', 'Curitiba', 'PR'),
(32, 'Cash Durham', 'Rua Gutermberg, 790', 'Curitiba', 'PR'),
(33, 'Tiffany Parrish', 'Rua das Estrelas, 372', 'São Paulo', 'SP'),
(34, 'Karsyn Rocha', 'Rua das Estrelas, 870', 'Recife', 'PE'),
(35, 'Emmie McPherson', 'Rua Neves Cruz, 473', 'Recife', 'PE'),
(36, 'Foster Newman', 'Rua Neves Cruz, 701', 'Rio de Janeiro', 'RJ'),
(37, 'Oaklynn Short', 'Rua Santos Silva, 563', 'Brasília', 'DF'),
(38, 'Hezekiah Cline', 'Rua Lopes Lima, 828', 'Brasília', 'DF'),
(39, 'Lina Harper', 'Rua Arnaldo Cruz, 507', 'Brasília', 'DF'),
(40, 'Hayes Huerta', 'Rua Santos Silva, 212', 'Recife', 'PE'),
(41, 'Dulce Marin', 'Rua das Estrelas, 599', 'Rio de Janeiro', 'RJ'),
(42, 'Aldo Villa', 'Rua das Laranjeiras, 858', 'Fortaleza', 'CE'),
(43, 'Johanna Horn', 'Rua Reinaldo Lemos, 391', 'Porto Alegre', 'RS'),
(44, 'Wilson Allen', 'Rua Gustavo Silva, 611', 'Recife', 'PE'),
(45, 'Riley McPherson', 'Rua das Borboletas, 436', 'Curitiba', 'PR'),
(46, 'Foster Cantu', 'Rua Maria Santidade, 449', 'Manaus', 'AM'),
(47, 'Galilea Barajas', 'Rua Neves Cruz, 174', 'Rio de Janeiro', 'RJ'),
(48, 'Brennan Casey', 'Rua Arnaldo Cruz, 615', 'Recife', 'PE'),
(49, 'Sylvia Glass', 'Rua Santos Silva, 391', 'Curitiba', 'PR'),
(50, 'Allan Saunders', 'Rua Gama Rei, 752', 'Brasília', 'DF'),
(51, 'Meadow Joseph', 'Rua das Estrelas, 581', 'Belo Horizonte', 'MG'),
(52, 'Kyle Beard', 'Rua Van Deuterno, 970', 'Rio de Janeiro', 'RJ'),
(53, 'Ezra Anthony', 'Rua Dimas, 411', 'Brasília', 'DF'),
(54, 'Shiloh Callahan', 'Rua das Estrelas, 473', 'Salvador', 'BA'),
(55, 'Kimber Vega', 'Rua das Borboletas, 376', 'Belo Horizonte', 'MG'),
(56, 'Aidan Olson', 'Rua Gutermberg, 248', 'Brasília', 'DF'),
(57, 'Isabel Brooks', 'Rua Meireles Cunha, 355', 'Recife', 'PE'),
(58, 'Jordan Harmon', 'Rua Gustavo Alegre, 500', 'Recife', 'PE'),
(59, 'Maren Peterson', 'Rua Van Deuterno, 932', 'Porto Alegre', 'RS'),
(60, 'Santiago Meadows', 'Rua Dimas, 901', 'Fortaleza', 'CE'),
(61, 'Pearl Cortes', 'Rua Marcelo dos Reis, 318', 'Salvador', 'BA'),
(62, 'Banks Beard', 'Rua Gustavo Silva, 307', 'Curitiba', 'PR'),
(63, 'Ezra Fischer', 'Rua Marcelo dos Reis, 229', 'Belo Horizonte', 'MG'),
(64, 'Leonidas Greer', 'Rua Gama Rei, 241', 'Salvador', 'BA'),
(65, 'Reina Calderon', 'Rua Neves Cruz, 806', 'Rio de Janeiro', 'RJ'),
(66, 'Oakley Monroe', 'Rua Gutermberg, 318', 'Belo Horizonte', 'MG'),
(67, 'Carly Glover', 'Rua das Estrelas, 163', 'Manaus', 'AM'),
(68, 'Mack Munoz', 'Rua Gutermberg, 365', 'São Paulo', 'SP'),
(69, 'Kehlani Meyers', 'Rua Dimas, 579', 'Curitiba', 'PR'),
(70, 'Julien Manning', 'Rua das Estrelas, 262', 'Brasília', 'DF'),
(71, 'Jennifer Cabrera', 'Rua Maria Santidade, 847', 'Manaus', 'AM'),
(72, 'Cade Warren', 'Rua Arnaldo Cruz, 268', 'São Paulo', 'SP'),
(73, 'Sloane Horton', 'Rua Gutermberg, 854', 'Rio de Janeiro', 'RJ'),
(74, 'Garrett Herring', 'Rua Maria Santidade, 640', 'Belo Horizonte', 'MG'),
(75, 'Denver Howard', 'Rua Arnaldo Cruz, 127', 'Manaus', 'AM'),
(76, 'Jeremiah Yates', 'Rua Santos Silva, 203', 'Curitiba', 'PR'),
(77, 'Charley Bradshaw', 'Rua Dimas, 823', 'Fortaleza', 'CE'),
(78, 'Emory Bullock', 'Rua Gustavo Silva, 351', 'Salvador', 'BA'),
(79, 'Winnie Ibarra', 'Rua Maria Santidade, 361', 'Manaus', 'AM'),
(80, 'Asa Escobar', 'Rua das Laranjeiras, 384', 'Manaus', 'AM'),
(81, 'Erin Casey', 'Rua Neves Cruz, 873', 'Recife', 'PE'),
(82, 'Armando Daniel', 'Rua Maria Santidade, 167', 'São Paulo', 'SP'),
(83, 'Joy Bowman', 'Rua Gustavo Silva, 213', 'Rio de Janeiro', 'RJ'),
(84, 'Francisco Castillo', 'Rua Gutermberg, 176', 'Porto Alegre', 'RS'),
(85, 'Eva Winters', 'Rua das Estrelas, 754', 'Curitiba', 'PR'),
(86, 'Deandre O’Donnell', 'Rua Gustavo Alegre, 539', 'Brasília', 'DF'),
(87, 'Bellamy Costa', 'Rua Gama Rei, 918', 'Porto Alegre', 'RS'),
(88, 'Kenji Dennis', 'Rua Gutermberg, 992', 'Belo Horizonte', 'MG'),
(89, 'Maisie Andrews', 'Rua Dimas, 209', 'Fortaleza', 'CE'),
(90, 'Lukas Hardy', 'Rua Santos Silva, 969', 'Rio de Janeiro', 'RJ'),
(91, 'Jessica McFarland', 'Rua Gustavo Alegre, 107', 'Manaus', 'AM'),
(92, 'Dane Stafford', 'Rua das Laranjeiras, 253', 'Brasília', 'DF'),
(93, 'Bridget Dickerson', 'Rua Arnaldo Cruz, 377', 'São Paulo', 'SP'),
(94, 'Flynn Bowman', 'Rua Maria Santidade, 835', 'Curitiba', 'PR'),
(95, 'Fiona Odom', 'Rua das Estrelas, 529', 'Recife', 'PE'),
(96, 'Kylian Estes', 'Rua Gustavo Alegre, 670', 'Porto Alegre', 'RS'),
(97, 'Brittany Brennan', 'Rua Gustavo Silva, 699', 'Belo Horizonte', 'MG'),
(98, 'Curtis Turner', 'Rua Dimas, 278', 'Brasília', 'DF'),
(99, 'Brooklyn Robbins', 'Rua Lopes Lima, 872', 'Curitiba', 'PR'),
(100, 'Finnegan Parsons', 'Rua Meireles Cunha, 814', 'Rio de Janeiro', 'RJ'),
(101, 'Maia Marks', 'Rua das Laranjeiras, 614', 'Belo Horizonte', 'MG'),
(102, 'Amos Shepherd', 'Rua Neves Cruz, 493', 'Brasília', 'DF'),
(103, 'Katalina Farrell', 'Rua Gustavo Silva, 983', 'Curitiba', 'PR'),
(104, 'Ty Berg', 'Rua Gustavo Alegre, 874', 'São Paulo', 'SP'),
(105, 'Emmalyn Castillo', 'Rua das Laranjeiras, 855', 'Manaus', 'AM'),
(106, 'Kai Palmer', 'Rua das Borboletas, 142', 'Salvador', 'BA'),
(107, 'Juniper Beasley', 'Rua Maria Santidade, 468', 'Rio de Janeiro', 'RJ'),
(108, 'Stanley Mack', 'Rua das Borboletas, 845', 'São Paulo', 'SP'),
(109, 'Nadia Luna', 'Rua Reinaldo Lemos, 182', 'Recife', 'PE'),
(110, 'Erick Spears', 'Rua Maria Santidade, 835', 'Curitiba', 'PR'),
(111, 'Isabela Villarreal', 'Rua Gustavo Silva, 443', 'Rio de Janeiro', 'RJ'),
(112, 'Nikolai Cross', 'Rua das Estrelas, 171', 'São Paulo', 'SP'),
(113, 'Nayeli Walters', 'Rua das Laranjeiras, 292', 'Salvador', 'BA'),
(114, 'Colson Pratt', 'Rua Lopes Lima, 351', 'Fortaleza', 'CE'),
(115, 'Ailani Campos', 'Rua Van Deuterno, 620', 'Manaus', 'AM'),
(116, 'Gideon Brooks', 'Rua das Borboletas, 165', 'São Paulo', 'SP'),
(117, 'Autumn Hardin', 'Rua Reinaldo Lemos, 492', 'Brasília', 'DF'),
(118, 'Hassan Robbins', 'Rua Van Deuterno, 889', 'Brasília', 'DF'),
(119, 'Stevie Larson', 'Rua das Laranjeiras, 519', 'Brasília', 'DF'),
(120, 'Rafael Massey', 'Rua Lopes Lima, 990', 'Brasília', 'DF'),
(121, 'Clementine Reyna', 'Rua Arnaldo Cruz, 271', 'Curitiba', 'PR'),
(122, 'Reginald Harris', 'Rua Marcelo dos Reis, 638', 'Rio de Janeiro', 'RJ'),
(123, 'Penelope English', 'Rua Gustavo Alegre, 863', 'Porto Alegre', 'RS'),
(124, 'Junior Blevins', 'Rua Neves Cruz, 348', 'Curitiba', 'PR'),
(125, 'Aila Montgomery', 'Rua Maria Santidade, 721', 'Curitiba', 'PR'),
(126, 'Maximiliano Bush', 'Rua Arnaldo Cruz, 280', 'Brasília', 'DF'),
(127, 'Everlee Barber', 'Rua Meireles Cunha, 510', 'Porto Alegre', 'RS'),
(128, 'Solomon Mendoza', 'Rua das Estrelas, 861', 'Fortaleza', 'CE'),
(129, 'Cora Christensen', 'Rua Gustavo Silva, 972', 'São Paulo', 'SP'),
(130, 'Gregory Bullock', 'Rua Santos Silva, 194', 'Manaus', 'AM'),
(131, 'Winnie Cortes', 'Rua das Borboletas, 509', 'Salvador', 'BA'),
(132, 'Banks Powers', 'Rua Van Deuterno, 675', 'Curitiba', 'PR'),
(133, 'Michelle Manning', 'Rua Maria Santidade, 188', 'Rio de Janeiro', 'RJ'),
(134, 'Seth Clark', 'Rua Dimas, 294', 'Fortaleza', 'CE'),
(135, 'Chloe Hill', 'Rua Gutermberg, 826', 'Porto Alegre', 'RS'),
(136, 'Isaac Fitzgerald', 'Rua Maria Santidade, 470', 'São Paulo', 'SP'),
(137, 'Marlee Moreno', 'Rua das Laranjeiras, 456', 'Manaus', 'AM'),
(138, 'Myles Robbins', 'Rua Gustavo Alegre, 601', 'Recife', 'PE'),
(139, 'Stevie Alfaro', 'Rua Meireles Cunha, 998', 'Curitiba', 'PR'),
(140, 'Xzavier Park', 'Rua Gutermberg, 947', 'Brasília', 'DF'),
(141, 'Lia Duran', 'Rua das Estrelas, 263', 'Manaus', 'AM'),
(142, 'Ismael Houston', 'Rua das Laranjeiras, 830', 'Rio de Janeiro', 'RJ'),
(143, 'Lylah Stanley', 'Rua Lopes Lima, 668', 'Recife', 'PE'),
(144, 'Manuel Dean', 'Rua Dimas, 756', 'Recife', 'PE'),
(145, 'Julianna Gutierrez', 'Rua Lopes Lima, 837', 'Belo Horizonte', 'MG'),
(146, 'Luca Hoffman', 'Rua Maria Santidade, 403', 'Curitiba', 'PR'),
(147, 'Aspen Yates', 'Rua Gustavo Alegre, 770', 'Brasília', 'DF'),
(148, 'Braylon Roy', 'Rua Gustavo Silva, 111', 'Recife', 'PE'),
(149, 'Savanna O’Neal', 'Rua Van Deuterno, 748', 'Porto Alegre', 'RS'),
(150, 'Eddie Shelton', 'Rua Dimas, 959', 'Rio de Janeiro', 'RJ'),
(151, 'Makenzie Patrick', 'Rua Santos Silva, 535', 'Porto Alegre', 'RS'),
(152, 'Derrick Richardson', 'Rua das Borboletas, 676', 'Porto Alegre', 'RS'),
(153, 'Allison Dillon', 'Rua das Borboletas, 465', 'Fortaleza', 'CE'),
(154, 'Alvin Brady', 'Rua Gama Rei, 173', 'Salvador', 'BA'),
(155, 'Ryan Wilkins', 'Rua Neves Cruz, 464', 'Recife', 'PE'),
(156, 'Yusuf Benjamin', 'Rua Gutermberg, 876', 'Belo Horizonte', 'MG'),
(157, 'Jianna Browning', 'Rua Gutermberg, 962', 'Fortaleza', 'CE'),
(158, 'Rohan Moody', 'Rua Gutermberg, 925', 'Porto Alegre', 'RS'),
(159, 'Elaine Flowers', 'Rua das Estrelas, 519', 'Rio de Janeiro', 'RJ'),
(160, 'Saul Duran', 'Rua Gama Rei, 274', 'Belo Horizonte', 'MG'),
(161, 'Willa Martin', 'Rua Reinaldo Lemos, 723', 'São Paulo', 'SP'),
(162, 'Mateo Roberts', 'Rua Dimas, 205', 'Brasília', 'DF'),
(163, 'Paisley Jaramillo', 'Rua Gama Rei, 786', 'Rio de Janeiro', 'RJ'),
(164, 'Riggs Collins', 'Rua Gutermberg, 632', 'Belo Horizonte', 'MG'),
(165, 'Kinsley Crane', 'Rua Meireles Cunha, 457', 'Recife', 'PE'),
(166, 'Fox Krueger', 'Rua Santos Silva, 677', 'Recife', 'PE'),
(167, 'Kamari Castaneda', 'Rua Gustavo Alegre, 449', 'Rio de Janeiro', 'RJ'),
(168, 'Collin Baker', 'Rua Lopes Lima, 954', 'Curitiba', 'PR'),
(169, 'Isla Bell', 'Rua Gustavo Alegre, 449', 'Salvador', 'BA'),
(170, 'Emmett Huang', 'Rua Gustavo Alegre, 909', 'Belo Horizonte', 'MG'),
(171, 'Francesca Wilkinson', 'Rua Lopes Lima, 761', 'Brasília', 'DF'),
(172, 'Leonard Huang', 'Rua Lopes Lima, 731', 'Belo Horizonte', 'MG'),
(173, 'Francesca Ballard', 'Rua Van Deuterno, 656', 'Recife', 'PE'),
(174, 'Kenzo Hale', 'Rua Gustavo Silva, 541', 'Curitiba', 'PR'),
(175, 'Brinley Melendez', 'Rua das Laranjeiras, 636', 'Belo Horizonte', 'MG'),
(176, 'Nikolas Chung', 'Rua Reinaldo Lemos, 628', 'Rio de Janeiro', 'RJ'),
(177, 'Rivka Welch', 'Rua Reinaldo Lemos, 324', 'Salvador', 'BA'),
(178, 'Hendrix Floyd', 'Rua das Borboletas, 529', 'Brasília', 'DF'),
(179, 'Yaretzi Frost', 'Rua Reinaldo Lemos, 794', 'Fortaleza', 'CE'),
(180, 'Dario Prince', 'Rua Santos Silva, 686', 'Recife', 'PE'),
(181, 'Greta Gould', 'Rua Gustavo Alegre, 550', 'Brasília', 'DF'),
(182, 'Blaine Porter', 'Rua Santos Silva, 352', 'Manaus', 'AM'),
(183, 'Ryleigh Kim', 'Rua Meireles Cunha, 834', 'Brasília', 'DF'),
(184, 'Roman Bravo', 'Rua Gama Rei, 216', 'São Paulo', 'SP'),
(185, 'Amoura Lawrence', 'Rua Neves Cruz, 684', 'Belo Horizonte', 'MG'),
(186, 'Kaleb Zavala', 'Rua Gustavo Silva, 130', 'Porto Alegre', 'RS'),
(187, 'Liv Lynch', 'Rua Gutermberg, 149', 'Manaus', 'AM'),
(188, 'Zane Marshall', 'Rua Arnaldo Cruz, 989', 'São Paulo', 'SP'),
(189, 'Adalyn Clayton', 'Rua Gutermberg, 847', 'Manaus', 'AM'),
(190, 'Boston Huang', 'Rua Maria Santidade, 912', 'Manaus', 'AM'),
(191, 'Francesca Hayden', 'Rua Lopes Lima, 512', 'Curitiba', 'PR'),
(192, 'Leroy Poole', 'Rua Maria Santidade, 409', 'Brasília', 'DF'),
(193, 'Bonnie Cabrera', 'Rua Dimas, 353', 'Belo Horizonte', 'MG'),
(194, 'Cade Walker', 'Rua Lopes Lima, 931', 'Rio de Janeiro', 'RJ'),
(195, 'Hazel Sellers', 'Rua Gama Rei, 778', 'Salvador', 'BA'),
(196, 'Madden House', 'Rua Gustavo Silva, 153', 'Brasília', 'DF'),
(197, 'Sariah Middleton', 'Rua das Laranjeiras, 158', 'Brasília', 'DF'),
(198, 'Misael Whitney', 'Rua Gustavo Silva, 931', 'Recife', 'PE'),
(199, 'Madalynn Farley', 'Rua das Borboletas, 210', 'Salvador', 'BA'),
(200, 'Graysen Arias', 'Rua das Laranjeiras, 179', 'Belo Horizonte', 'MG'),
(201, 'Aleah Allison', 'Rua Neves Cruz, 197', 'Recife', 'PE'),
(202, 'Dennis Bryan', 'Rua Van Deuterno, 431', 'Rio de Janeiro', 'RJ'),
(203, 'Meredith Coleman', 'Rua Gama Rei, 483', 'Brasília', 'DF'),
(204, 'Micah Parker', 'Rua Neves Cruz, 933', 'Brasília', 'DF'),
(205, 'Aubrey Ryan', 'Rua Marcelo dos Reis, 114', 'Porto Alegre', 'RS'),
(206, 'Timothy Hubbard', 'Rua Lopes Lima, 416', 'Brasília', 'DF'),
(207, 'Rosie Scott', 'Rua Maria Santidade, 226', 'Manaus', 'AM'),
(208, 'Leo Campbell', 'Rua Van Deuterno, 481', 'Manaus', 'AM'),
(209, 'Addison Neal', 'Rua Marcelo dos Reis, 907', 'Rio de Janeiro', 'RJ'),
(210, 'Kane Sharp', 'Rua Arnaldo Cruz, 377', 'São Paulo', 'SP'),
(211, 'Camryn Roman', 'Rua Reinaldo Lemos, 311', 'Manaus', 'AM'),
(212, 'Kian Randall', 'Rua Lopes Lima, 584', 'Curitiba', 'PR'),
(213, 'Christina Miles', 'Rua Gustavo Silva, 399', 'Belo Horizonte', 'MG'),
(214, 'Jared Suarez', 'Rua das Estrelas, 681', 'Salvador', 'BA'),
(215, 'Jimena Howard', 'Rua Gutermberg, 421', 'Manaus', 'AM'),
(216, 'Jeremiah McPherson', 'Rua Dimas, 350', 'Porto Alegre', 'RS'),
(217, 'Emmaline Huber', 'Rua Meireles Cunha, 605', 'Brasília', 'DF'),
(218, 'Mac Bowman', 'Rua Van Deuterno, 569', 'Manaus', 'AM'),
(219, 'Fiona Esparza', 'Rua das Estrelas, 212', 'Rio de Janeiro', 'RJ'),
(220, 'Carl Schwartz', 'Rua Neves Cruz, 139', 'Curitiba', 'PR'),
(221, 'Lilliana Crawford', 'Rua Maria Santidade, 627', 'Fortaleza', 'CE'),
(222, 'Kevin Yates', 'Rua das Estrelas, 820', 'Recife', 'PE'),
(223, 'Charley Owens', 'Rua Reinaldo Lemos, 669', 'Manaus', 'AM'),
(224, 'Adriel David', 'Rua das Laranjeiras, 737', 'Porto Alegre', 'RS'),
(225, 'Haylee Leal', 'Rua Van Deuterno, 980', 'Porto Alegre', 'RS'),
(226, 'Cedric Cardenas', 'Rua Dimas, 933', 'Curitiba', 'PR'),
(227, 'Raven Hess', 'Rua Maria Santidade, 977', 'Rio de Janeiro', 'RJ'),
(228, 'Lawrence Dyer', 'Rua Santos Silva, 805', 'Brasília', 'DF'),
(229, 'Estrella Monroe', 'Rua Gama Rei, 547', 'Salvador', 'BA'),
(230, 'Colby Estrada', 'Rua das Estrelas, 949', 'Salvador', 'BA'),
(231, 'Sawyer Fry', 'Rua Neves Cruz, 692', 'Fortaleza', 'CE'),
(232, 'Jacoby Guevara', 'Rua Reinaldo Lemos, 565', 'Curitiba', 'PR'),
(233, 'Teresa Stafford', 'Rua Reinaldo Lemos, 173', 'Belo Horizonte', 'MG'),
(234, 'Alfredo Banks', 'Rua das Estrelas, 244', 'Porto Alegre', 'RS'),
(235, 'Cali Hutchinson', 'Rua das Laranjeiras, 600', 'Brasília', 'DF'),
(236, 'Korbin Montes', 'Rua Neves Cruz, 774', 'Porto Alegre', 'RS'),
(237, 'Roselyn Middleton', 'Rua Meireles Cunha, 669', 'São Paulo', 'SP'),
(238, 'Misael Lawrence', 'Rua das Borboletas, 418', 'Rio de Janeiro', 'RJ'),
(239, 'Lauren Howard', 'Rua das Borboletas, 902', 'Rio de Janeiro', 'RJ'),
(240, 'Jeremiah Owen', 'Rua Dimas, 267', 'Salvador', 'BA'),
(241, 'Mikayla Rush', 'Rua Gama Rei, 303', 'Fortaleza', 'CE'),
(242, 'Kaiser McCarthy', 'Rua Reinaldo Lemos, 533', 'Belo Horizonte', 'MG'),
(243, 'Kira Hall', 'Rua das Borboletas, 605', 'Belo Horizonte', 'MG'),
(244, 'Thomas Bernal', 'Rua Meireles Cunha, 206', 'Porto Alegre', 'RS'),
(245, 'Emmeline Moyer', 'Rua das Laranjeiras, 439', 'Manaus', 'AM'),
(246, 'Ahmir Salas', 'Rua Maria Santidade, 277', 'Recife', 'PE'),
(247, 'Amber Cordova', 'Rua Arnaldo Cruz, 659', 'Salvador', 'BA'),
(248, 'Vicente Morrison', 'Rua Maria Santidade, 633', 'Fortaleza', 'CE'),
(249, 'Rebecca Boyd', 'Rua Marcelo dos Reis, 325', 'Salvador', 'BA'),
(250, 'Dean Franklin', 'Rua Santos Silva, 360', 'Brasília', 'DF'),
(251, 'Angela Swanson', 'Rua Lopes Lima, 243', 'Manaus', 'AM'),
(252, 'Hugo Carlson', 'Rua Marcelo dos Reis, 426', 'Brasília', 'DF'),
(253, 'Kali Lyons', 'Rua Marcelo dos Reis, 719', 'Recife', 'PE'),
(254, 'Cyrus Schneider', 'Rua Santos Silva, 638', 'Recife', 'PE'),
(255, 'Delaney Reeves', 'Rua das Borboletas, 102', 'Salvador', 'BA'),
(256, 'Clark Mendoza', 'Rua Maria Santidade, 521', 'Brasília', 'DF'),
(257, 'Cora Gilbert', 'Rua Gama Rei, 415', 'Fortaleza', 'CE'),
(258, 'Tobias Tate', 'Rua Maria Santidade, 451', 'Belo Horizonte', 'MG'),
(259, 'Skye Osborne', 'Rua Gustavo Alegre, 132', 'Curitiba', 'PR'),
(260, 'Augustus Khan', 'Rua Neves Cruz, 343', 'Curitiba', 'PR'),
(261, 'Mabel Bauer', 'Rua Dimas, 338', 'Rio de Janeiro', 'RJ'),
(262, 'Kieran Palmer', 'Rua Reinaldo Lemos, 969', 'Porto Alegre', 'RS'),
(263, 'Juniper Newman', 'Rua Lopes Lima, 105', 'Brasília', 'DF'),
(264, 'Anderson Bonilla', 'Rua das Borboletas, 597', 'Porto Alegre', 'RS'),
(265, 'Romina Franco', 'Rua das Borboletas, 963', 'Porto Alegre', 'RS'),
(266, 'Gage Porter', 'Rua Neves Cruz, 298', 'Rio de Janeiro', 'RJ'),
(267, 'Ryleigh Wiley', 'Rua Neves Cruz, 261', 'Recife', 'PE'),
(268, 'Mathew Knight', 'Rua Maria Santidade, 570', 'Belo Horizonte', 'MG'),
(269, 'Gracie Leon', 'Rua das Laranjeiras, 932', 'Brasília', 'DF'),
(270, 'Marshall Simon', 'Rua das Laranjeiras, 665', 'Salvador', 'BA'),
(271, 'Kalani Haley', 'Rua Gutermberg, 890', 'Rio de Janeiro', 'RJ'),
(272, 'Leif Robbins', 'Rua das Laranjeiras, 432', 'Belo Horizonte', 'MG'),
(273, 'Stevie Chang', 'Rua Van Deuterno, 228', 'Belo Horizonte', 'MG'),
(274, 'Ari Dickerson', 'Rua Neves Cruz, 529', 'Brasília', 'DF'),
(275, 'Opal Young', 'Rua Santos Silva, 431', 'Belo Horizonte', 'MG'),
(276, 'Asher Berry', 'Rua Maria Santidade, 933', 'Manaus', 'AM'),
(277, 'Annabelle Compton', 'Rua Meireles Cunha, 858', 'Recife', 'PE'),
(278, 'Abner Lowery', 'Rua Van Deuterno, 242', 'Belo Horizonte', 'MG'),
(279, 'Estelle Benitez', 'Rua Lopes Lima, 780', 'Salvador', 'BA'),
(280, 'Justice Shelton', 'Rua Gustavo Alegre, 570', 'Fortaleza', 'CE'),
(281, 'Makenzie Williamson', 'Rua Reinaldo Lemos, 904', 'Brasília', 'DF'),
(282, 'Emerson Suarez', 'Rua das Borboletas, 476', 'Recife', 'PE'),
(283, 'Jimena Marks', 'Rua das Laranjeiras, 624', 'Salvador', 'BA'),
(284, 'Amos Quintero', 'Rua Neves Cruz, 472', 'Recife', 'PE'),
(285, 'Keyla Guevara', 'Rua Arnaldo Cruz, 387', 'Brasília', 'DF'),
(286, 'Tommy Tyler', 'Rua Arnaldo Cruz, 178', 'Porto Alegre', 'RS'),
(287, 'Helena Francis', 'Rua Marcelo dos Reis, 989', 'Belo Horizonte', 'MG'),
(288, 'Harvey Bowman', 'Rua Gama Rei, 831', 'Rio de Janeiro', 'RJ'),
(289, 'Fiona Dickerson', 'Rua Santos Silva, 331', 'Belo Horizonte', 'MG'),
(290, 'Flynn Harris', 'Rua Lopes Lima, 255', 'Fortaleza', 'CE'),
(291, 'Penelope McFarland', 'Rua Neves Cruz, 614', 'Belo Horizonte', 'MG'),
(292, 'Dane Campbell', 'Rua Meireles Cunha, 166', 'Recife', 'PE'),
(293, 'Addison Solomon', 'Rua Van Deuterno, 178', 'São Paulo', 'SP'),
(294, 'Musa Avalos', 'Rua Dimas, 822', 'Rio de Janeiro', 'RJ'),
(295, 'Paloma Richards', 'Rua das Borboletas, 822', 'Fortaleza', 'CE'),
(296, 'Holden Moyer', 'Rua Dimas, 703', 'Belo Horizonte', 'MG'),
(297, 'Zola Soto', 'Rua Maria Santidade, 127', 'Rio de Janeiro', 'RJ'),
(298, 'Barrett Velez', 'Rua Gutermberg, 968', 'Belo Horizonte', 'MG'),
(299, 'Megan Leonard', 'Rua Dimas, 906', 'Salvador', 'BA'),
(300, 'Ricardo Hicks', 'Rua Santos Silva, 238', 'Recife', 'PE'),
(301, 'Alina Meyer', 'Rua das Laranjeiras, 297', 'Salvador', 'BA'),
(302, 'Tristan Pena', 'Rua Lopes Lima, 266', 'Curitiba', 'PR'),
(303, 'Rachel Sanford', 'Rua Gama Rei, 671', 'Curitiba', 'PR'),
(304, 'Truett Salas', 'Rua Gustavo Alegre, 152', 'Salvador', 'BA'),
(305, 'Amber Reynolds', 'Rua Meireles Cunha, 256', 'Brasília', 'DF'),
(306, 'Vincent Morse', 'Rua das Borboletas, 296', 'Curitiba', 'PR'),
(307, 'Kairi Marks', 'Rua Neves Cruz, 195', 'Rio de Janeiro', 'RJ'),
(308, 'Amos Kemp', 'Rua Maria Santidade, 963', 'São Paulo', 'SP'),
(309, 'Anika Nichols', 'Rua Dimas, 367', 'Curitiba', 'PR'),
(310, 'Atlas Golden', 'Rua Maria Santidade, 546', 'Recife', 'PE'),
(311, 'Giuliana Fitzgerald', 'Rua Maria Santidade, 231', 'Rio de Janeiro', 'RJ'),
(312, 'Peyton Macias', 'Rua Gustavo Silva, 189', 'Rio de Janeiro', 'RJ'),
(313, 'Adley Beck', 'Rua Van Deuterno, 228', 'Salvador', 'BA'),
(314, 'Eduardo Poole', 'Rua Santos Silva, 944', 'Porto Alegre', 'RS'),
(315, 'Bonnie Ward', 'Rua Van Deuterno, 534', 'Belo Horizonte', 'MG'),
(316, 'Jameson Ibarra', 'Rua Arnaldo Cruz, 922', 'Salvador', 'BA'),
(317, 'Madilynn McConnell', 'Rua Reinaldo Lemos, 985', 'Belo Horizonte', 'MG'),
(318, 'London Khan', 'Rua Neves Cruz, 906', 'Salvador', 'BA'),
(319, 'Mabel Kemp', 'Rua Gustavo Alegre, 944', 'Fortaleza', 'CE'),
(320, 'Melvin Woodard', 'Rua Van Deuterno, 454', 'Salvador', 'BA'),
(321, 'Aubrie Schneider', 'Rua das Laranjeiras, 996', 'Salvador', 'BA'),
(322, 'Raymond Ventura', 'Rua Lopes Lima, 872', 'Recife', 'PE'),
(323, 'Zora Larsen', 'Rua Arnaldo Cruz, 512', 'Fortaleza', 'CE'),
(324, 'Brycen Wood', 'Rua Neves Cruz, 836', 'Recife', 'PE'),
(325, 'Natalia Norton', 'Rua Meireles Cunha, 660', 'Rio de Janeiro', 'RJ'),
(326, 'Callen McMillan', 'Rua Meireles Cunha, 439', 'Fortaleza', 'CE'),
(327, 'Oakleigh Henson', 'Rua das Estrelas, 196', 'São Paulo', 'SP'),
(328, 'Bellamy McIntosh', 'Rua Meireles Cunha, 630', 'Rio de Janeiro', 'RJ'),
(329, 'Gwen Giles', 'Rua Gama Rei, 546', 'Recife', 'PE'),
(330, 'Kole Watts', 'Rua Gutermberg, 485', 'Curitiba', 'PR'),
(331, 'Melissa McCarthy', 'Rua Lopes Lima, 820', 'Belo Horizonte', 'MG'),
(332, 'Devin Clay', 'Rua Neves Cruz, 254', 'Porto Alegre', 'RS'),
(333, 'Aliana Wolfe', 'Rua Gama Rei, 844', 'Fortaleza', 'CE'),
(334, 'Donovan Terry', 'Rua Gustavo Alegre, 912', 'Fortaleza', 'CE'),
(335, 'Wren Patterson', 'Rua Maria Santidade, 952', 'Rio de Janeiro', 'RJ'),
(336, 'Amir Harris', 'Rua Dimas, 310', 'Recife', 'PE'),
(337, 'Penelope Flynn', 'Rua Arnaldo Cruz, 841', 'Fortaleza', 'CE'),
(338, 'Kannon Stuart', 'Rua Gama Rei, 523', 'Brasília', 'DF'),
(339, 'Stormi Weeks', 'Rua Lopes Lima, 266', 'Curitiba', 'PR'),
(340, 'Anders Fleming', 'Rua Lopes Lima, 482', 'Manaus', 'AM'),
(341, 'Fatima Schroeder', 'Rua Gustavo Alegre, 268', 'Manaus', 'AM'),
(342, 'Izaiah Vaughn', 'Rua das Estrelas, 912', 'Brasília', 'DF'),
(343, 'Reign Morales', 'Rua Reinaldo Lemos, 902', 'Recife', 'PE'),
(344, 'Aaron Mata', 'Rua das Borboletas, 521', 'Fortaleza', 'CE'),
(345, 'Lillie Bonilla', 'Rua das Estrelas, 420', 'Recife', 'PE'),
(346, 'Aden Aguilar', 'Rua Neves Cruz, 238', 'Brasília', 'DF'),
(347, 'Josie Golden', 'Rua Arnaldo Cruz, 880', 'Manaus', 'AM'),
(348, 'Amias Bates', 'Rua Gutermberg, 568', 'Belo Horizonte', 'MG'),
(349, 'Madilyn Alfaro', 'Rua Gustavo Alegre, 849', 'Recife', 'PE'),
(350, 'Xzavier Flowers', 'Rua Meireles Cunha, 522', 'Belo Horizonte', 'MG')

-- Inserts data in the table
INSERT INTO dw.DIM_SELLER (Registration, Name) VALUES
(1, 'Ariya Peterson'),
(2, 'Santiago Tang'),
(3, 'Belle Barry'),
(4, 'Emery Navarro'),
(5, 'Winter Cameron'),
(6, 'Rayan Pacheco'),
(7, 'Paris Benton'),
(8, 'Jamal Tate'),
(9, 'Skye Collins'),
(10, 'Miles York'),
(11, 'Milan Gentry'),
(12, 'Magnus Farley'),
(13, 'Wrenley Campbell'),
(14, 'Christopher Blair'),
(15, 'Frances McDaniel'),
(16, 'Major McDonald'),
(17, 'Daisy Johnson'),
(18, 'Noah Rogers'),
(19, 'Madelyn Noble'),
(20, 'Idris Carrillo'),
(21, 'Kaylani Hoffman'),
(22, 'Steven Cruz'),
(23, 'Claire Branch'),
(24, 'Keenan O’Connell'),
(25, 'Jillian Huynh'),
(26, 'Layton Branch'),
(27, 'Luisa Lucero'),
(28, 'Felipe Portillo'),
(29, 'Nathalie Townsend'),
(30, 'Alexis Burnett'),
(31, 'Emberly Jacobs'),
(32, 'Bryan Morgan'),
(33, 'Delilah Hill'),
(34, 'Isaac Myers'),
(35, 'Lydia Whitney'),
(36, 'Jeffery Campos'),
(37, 'Sutton Peck'),
(38, 'Yousef Weeks'),
(39, 'Karen Trevino'),
(40, 'Jaime Daniel'),
(41, 'Joy May'),
(42, 'Finley Carrillo'),
(43, 'Kaylani Quinn'),
(44, 'Rhys Byrd'),
(45, 'Giselle Ahmed'),
(46, 'Harry Zimmerman'),
(47, 'Ariyah Dunn'),
(48, 'Dawson Curry'),
(49, 'Alison Blevins'),
(50, 'Avi Ortega'),
(51, 'Lilah Johnson'),
(52, 'Noah Nelson'),
(53, 'Everly Daugherty'),
(54, 'Turner Olson'),
(55, 'Isabel Gould'),
(56, 'Blaine Stanton'),
(57, 'Jaycee Solomon'),
(58, 'Musa Fitzgerald'),
(59, 'Marlee Davidson'),
(60, 'Dante Rasmussen'),
(61, 'Esperanza Wolf'),
(62, 'Jase Richard'),
(63, 'Davina Dickson'),
(64, 'Maxton Wood'),
(65, 'Natalia McKenzie'),
(66, 'Scott Mullins'),
(67, 'Maliyah Saunders'),
(68, 'Kasen Osborne'),
(69, 'Shelby Sims'),
(70, 'Brian Phillips'),
(71, 'Naomi Cordova'),
(72, 'Vicente Whitney'),
(73, 'Madalynn Koch'),
(74, 'Salvador Dennis'),
(75, 'Maisie Baxter'),
(76, 'Tomas Howell'),
(77, 'Mckenna Flores'),
(78, 'Lincoln McCall'),
(79, 'Kai Green'),
(80, 'Anthony Parks'),
(81, 'Ainsley Hickman'),
(82, 'Jakobe Hudson'),
(83, 'Kamila Leon'),
(84, 'Marshall Farley'),
(85, 'Wrenley Yates'),
(86, 'Braylon Berger'),
(87, 'Laylah Love'),
(88, 'Jeffrey Bradshaw'),
(89, 'Berkley Shah'),
(90, 'Zain Hanna'),
(91, 'Cynthia Donovan'),
(92, 'Brayan Sheppard'),
(93, 'Veda McGuire'),
(94, 'Casey Macdonald'),
(95, 'Rosalia McLaughlin'),
(96, 'Ibrahim Jefferson'),
(97, 'Julieta English'),
(98, 'Junior Doyle'),
(99, 'Annalise Floyd'),
(100, 'Pierce Schmitt'),
(101, 'Queen Cannon'),
(102, 'Archie McDaniel'),
(103, 'Dahlia Santos'),
(104, 'Walker Parks'),
(105, 'Ainsley Horn'),
(106, 'Wilson Franco'),
(107, 'Charleigh Travis'),
(108, 'Willie Valentine'),
(109, 'August Hayden'),
(110, 'Leroy Benitez'),
(111, 'Aliza Reilly'),
(112, 'Alvaro Ibarra'),
(113, 'Madilynn Taylor'),
(114, 'Jackson Quintero'),
(115, 'Keyla Gonzales'),
(116, 'Brayden Wiggins'),
(117, 'Capri Chambers'),
(118, 'Orion Whitaker'),
(119, 'Ivanna Logan'),
(120, 'Rocco Cantrell'),
(121, 'Yamileth Abbott'),
(122, 'Kohen Knight'),
(123, 'Gracie Estes'),
(124, 'Hakeem Singleton'),
(125, 'Malaysia Kerr'),
(126, 'Louie Madden'),
(127, 'Violette Barker'),
(128, 'Kade Figueroa'),
(129, 'Lilith Savage'),
(130, 'Keaton Cordova'),
(131, 'Florence O’Neal'),
(132, 'Eddie Gould'),
(133, 'Violeta Stafford'),
(134, 'Alfredo Avery'),
(135, 'Meghan Foster'),
(136, 'Kayden Boyd'),
(137, 'Georgia O’Neill'),
(138, 'Marcel Cannon'),
(139, 'Noa Shepherd'),
(140, 'Ronald Barry'),
(141, 'Waverly Duarte'),
(142, 'Abdullah Mitchell'),
(143, 'Willow Crane'),
(144, 'Fox Christian'),
(145, 'Anahi Stout'),
(146, 'Callahan Clarke'),
(147, 'Kaitlyn Russell'),
(148, 'Weston Bridges'),
(149, 'Elora Pitts'),
(150, 'Trey Cannon'),
(151, 'Noa Atkins'),
(152, 'Cason Duncan'),
(153, 'Elise Xiong'),
(154, 'Azrael Bernal'),
(155, 'Emmeline Gill'),
(156, 'Matthias Maddox'),
(157, 'Zainab Harrington'),
(158, 'Omari Hahn'),
(159, 'Fallon Hutchinson'),
(160, 'Korbin King'),
(161, 'Victoria Howell'),
(162, 'Bradley Stokes'),
(163, 'Miranda Cervantes'),
(164, 'Kamari Chambers'),
(165, 'Makayla Pennington'),
(166, 'Bobby Larson'),
(167, 'Alayna Horton'),
(168, 'Garrett Roach'),
(169, 'Lyanna Haley'),
(170, 'Leif Shields'),
(171, 'Analia McDowell'),
(172, 'Lachlan Powell'),
(173, 'Vivian Livingston'),
(174, 'Ambrose McLaughlin'),
(175, 'Stephanie Cano'),
(176, 'Terry Moody'),
(177, 'Elaine Kemp'),
(178, 'Melvin Gregory'),
(179, 'Alaya Russell'),
(180, 'Weston Skinner'),
(181, 'Mara McLaughlin'),
(182, 'Ibrahim Barron'),
(183, 'Anya Cobb'),
(184, 'Raphael Wu'),
(185, 'Liana Tyler'),
(186, 'Emmitt Stanton'),
(187, 'Jaycee Roth'),
(188, 'Roy Santiago'),
(189, 'Nyla Rodriguez'),
(190, 'Henry Estes'),
(191, 'Brittany Hopkins'),
(192, 'Ali Patton'),
(193, 'Lorelei Brennan'),
(194, 'Curtis Murray'),
(195, 'Faith Weaver'),
(196, 'Tucker Golden'),
(197, 'Giuliana Cain'),
(198, 'Benson Ballard'),
(199, 'Alejandra Cain'),
(200, 'Benson Holloway'),
(201, 'Mae Briggs'),
(202, 'Case Tran'),
(203, 'Kylie Watkins'),
(204, 'Nash Farrell'),
(205, 'Kassidy Edwards'),
(206, 'Adrian Hamilton'),
(207, 'Mackenzie Robertson'),
(208, 'Emiliano Goodman'),
(209, 'Carolina Ryan'),
(210, 'Timothy Lowery'),
(211, 'Estelle Tucker'),
(212, 'Ivan Beasley'),
(213, 'Jaylah Gill'),
(214, 'Matthias O’Neill'),
(215, 'Kenna Wells'),
(216, 'Max Glover'),
(217, 'Alessia Frazier'),
(218, 'Callum Snyder'),
(219, 'Callie Nicholson'),
(220, 'Rodrigo Zhang'),
(221, 'Sarai Bruce'),
(222, 'Uriah Walker'),
(223, 'Hazel Booth'),
(224, 'Chaim Wise'),
(225, 'Mira Burnett'),
(226, 'Davis Lyons'),
(227, 'Kenzie Nichols'),
(228, 'Atlas Fernandez'),
(229, 'Amara Dawson'),
(230, 'Iker Lam'),
(231, 'Karina Edwards'),
(232, 'Adrian Ware'),
(233, 'Eileen Browning'),
(234, 'Rohan Maddox'),
(235, 'Zainab Fox'),
(236, 'Antonio Jensen'),
(237, 'Jane Tanner'),
(238, 'Bruno Curtis'),
(239, 'Alexis Moore'),
(240, 'Levi Pruitt'),
(241, 'Brylee Lugo'),
(242, 'Santos Fry'),
(243, 'Clarissa Washington'),
(244, 'Juan Nelson'),
(245, 'Everly Neal'),
(246, 'Kane Bryant'),
(247, 'Parker Hail'),
(248, 'Hector Ponce'),
(249, 'Aileen Brock'),
(250, 'Julio Beltran'),
(251, 'Kaydence Robles'),
(252, 'Otto Brown'),
(253, 'Charlotte Sanford'),
(254, 'Truett Abbott'),
(255, 'Melany Gibbs'),
(256, 'Deacon Silva'),
(257, 'Lucia Leblanc'),
(258, 'Braden Jones'),
(259, 'Sophia Garrett'),
(260, 'Kairo Vaughan'),
(261, 'Nancy Vang'),
(262, 'Jimmy Rocha'),
(263, 'Emmie Cline'),
(264, 'Cullen Shepard'),
(265, 'Noor Paul'),
(266, 'Noel Singleton'),
(267, 'Malaysia Brandt'),
(268, 'Damir Allison'),
(269, 'Chelsea Bullock'),
(270, 'Ben Sawyer'),
(271, 'Marina Lester'),
(272, 'Lee Enriquez'),
(273, 'Nellie Watkins'),
(274, 'Nash Tapia'),
(275, 'Michaela Bradford'),
(276, 'Ander Pace'),
(277, 'Giana Benjamin'),
(278, 'Kyro Potter'),
(279, 'Rory Sullivan'),
(280, 'Evan Blair'),
(281, 'Frances Ross'),
(282, 'Wesley Berg'),
(283, 'Emmalyn Chan'),
(284, 'Frank Berg'),
(285, 'Emmalyn Gray'),
(286, 'Nicholas Santana'),
(287, 'Myra Atkins'),
(288, 'Cason McConnell'),
(289, 'Denise Jennings'),
(290, 'Corbin Watts'),
(291, 'Melissa Sullivan'),
(292, 'Evan Webster'),
(293, 'Kensley Allison'),
(294, 'Dennis Hanna'),
(295, 'Cynthia Richmond'),
(296, 'Mordechai Leonard'),
(297, 'Demi Todd'),
(298, 'Baylor Jenkins'),
(299, 'Rylee Hart'),
(300, 'Joel Paul'),
(301, 'Daphne Mullen'),
(302, 'Shepard Martin'),
(303, 'Mila Compton'),
(304, 'Abner Harris'),
(305, 'Penelope Brennan'),
(306, 'Curtis Mendoza'),
(307, 'Cora Golden'),
(308, 'Amias Colon'),
(309, 'Remy Morse'),
(310, 'Bode Durham'),
(311, 'Tiffany Bowen'),
(312, 'Trevor Sexton'),
(313, 'Ellen Kirby'),
(314, 'Tony Boyd'),
(315, 'Georgia Cabrera'),
(316, 'Cade Miranda'),
(317, 'Amina Barker'),
(318, 'Kade Hughes'),
(319, 'Samantha Gonzalez'),
(320, 'Ethan Corona'),
(321, 'Marianna Singleton'),
(322, 'Landyn Mueller'),
(323, 'Imani Madden'),
(324, 'Everest Delgado'),
(325, 'Alani Quintana'),
(326, 'Kelvin Lambert'),
(327, 'Nina Haley'),
(328, 'Leif Taylor'),
(329, 'Sofia Zhang'),
(330, 'Isaias Ellison'),
(331, 'Raina Wiggins'),
(332, 'Azariah Burch'),
(333, 'Freyja Horton'),
(334, 'Garrett Armstrong'),
(335, 'Presley O’Connor'),
(336, 'Princeton Moreno'),
(337, 'Mary Gibbs'),
(338, 'Deacon Avalos'),
(339, 'Paloma Foley'),
(340, 'Mohammad Morales'),
(341, 'Skylar Escobar'),
(342, 'Zachariah Page'),
(343, 'Cataleya Willis'),
(344, 'Remington Peters'),
(345, 'Leila Costa'),
(346, 'Kenji Hartman'),
(347, 'Kennedi Carey'),
(348, 'Watson Whitney'),
(349, 'Madalynn Flynn'),
(350, 'Kannon Spence'),
(351, 'Aislinn Valdez'),
(352, 'Kyler Gardner'),
(353, 'Jordyn Bauer'),
(354, 'Kieran Hobbs'),
(355, 'Lacey Burton'),
(356, 'Zander Black'),
(357, 'Molly Sosa'),
(358, 'Emir Marks'),
(359, 'Monica Paul'),
(360, 'Noel Brewer'),
(361, 'Thea Dalton'),
(362, 'Fletcher Arnold'),
(363, 'Finley Gilmore'),
(364, 'Vihaan Hickman'),
(365, 'Scarlette Khan'),
(366, 'Kendrick Mejia'),
(367, 'Saylor Quintana'),
(368, 'Kelvin Curtis'),
(369, 'Alexis Xiong'),
(370, 'Azrael Olson'),
(371, 'Isabel Williamson'),
(372, 'Emerson Jimenez'),
(373, 'Adeline Hebert'),
(374, 'Guillermo Sanchez'),
(375, 'Aria Lambert'),
(376, 'Mario Fernandez'),
(377, 'Amara Lane'),
(378, 'Matias Ramirez'),
(379, 'Grace Richards'),
(380, 'Holden Nixon'),
(381, 'Deborah Casey'),
(382, 'Armando Elliott'),
(383, 'Noelle Leal'),
(384, 'Cedric Beltran'),
(385, 'Kaydence Campbell'),
(386, 'Christopher Weiss'),
(387, 'Lennox Robbins'),
(388, 'Finnegan Mueller'),
(389, 'Imani Hensley'),
(390, 'Layne Dillon'),
(391, 'Laurel Vaughn'),
(392, 'Remy Mayer'),
(393, 'Ainhoa Acosta'),
(394, 'Jensen Norton'),
(395, 'Kylee Ashley'),
(396, 'Kylen Valentine'),
(397, 'August Cochran'),
(398, 'Danny Bernard'),
(399, 'Barbara Dyer'),
(400, 'Atreus O’Connor');

-- Inserts data in the table
INSERT INTO dw.DIM_DATE (Full_date, Year_date, Month_date, Day_date)
SELECT 
    Full_date,
    EXTRACT(YEAR FROM Full_date) AS Year_date,
    EXTRACT(MONTH FROM Full_date) AS Month_date,
    EXTRACT(DAY FROM Full_date) AS Day_date
FROM generate_series('2023-01-01'::date, '2023-12-31'::date, '1 day'::interval) AS Full_date;

-- Create a sequence to generate sequential values ​​for the ID field
CREATE SEQUENCE transaction_seq;

-- Create function to load the fact table from the dimension tables
CREATE OR REPLACE FUNCTION dw.load_FACT_SALES()
RETURNS VOID AS $$
BEGIN
    -- Ensuring that at least 1000 unique records are inserted, repeating dimension data as necessary
    INSERT INTO dw.FACT_SALES (Date_, Product, Store, Seller, Client, Amount_sold, Total_sold, Transaction_ID)
    SELECT
        d.Full_date,
        p.SKU_Code,
        l.Code,
        v.Registration,
        c.Client_ID,
        (RANDOM() * 10 + 1)::INT AS Amount_sold,  -- Generates quantity sold between 1 and 10
        (RANDOM() * 1000 + 100)::NUMERIC(10,2) AS Total_sold,  -- Generates total sale value between 100 and 1100
        nextval('transaction_seq') AS Transaction_ID -- Sequence for transaction ID
    FROM
        (SELECT Full_date, ROW_NUMBER() OVER (ORDER BY RANDOM()) AS rn FROM dw.DIM_DATE) d
        JOIN (SELECT SKU_Code, ROW_NUMBER() OVER (ORDER BY RANDOM()) AS rn FROM dw.DIM_PRODUCT) p ON MOD(d.rn, (SELECT COUNT(*) FROM dw.DIM_PRODUCT)) = p.rn % (SELECT COUNT(*) FROM dw.DIM_PRODUCT)
        JOIN (SELECT Code, ROW_NUMBER() OVER (ORDER BY RANDOM()) AS rn FROM dw.DIM_STORE) l ON MOD(d.rn, (SELECT COUNT(*) FROM dw.DIM_STORE)) = l.rn % (SELECT COUNT(*) FROM dw.DIM_STORE)
        JOIN (SELECT Registration, ROW_NUMBER() OVER (ORDER BY RANDOM()) AS rn FROM dw.DIM_SELLER) v ON MOD(d.rn, (SELECT COUNT(*) FROM dw.DIM_SELLER)) = v.rn % (SELECT COUNT(*) FROM dw.DIM_SELLER)
        JOIN (SELECT Client_ID, ROW_NUMBER() OVER (ORDER BY RANDOM()) AS rn FROM dw.DIM_CLIENT) c ON MOD(d.rn, (SELECT COUNT(*) FROM dw.DIM_CLIENT)) = c.rn % (SELECT COUNT(*) FROM dw.DIM_CLIENT)
    WHERE d.rn <= 1000;  -- Limit insertion to the first 1000 records
END;
$$ LANGUAGE plpgsql;

-- Executes the function
SELECT dw.load_FACT_SALES();
